### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by chelmerrox** [gak92/Ghazanfar_Portfolio#6]
Awesome job! 💯👏🏽👏🏽👏🏽

- excellent & clear presentation of your code
- neat structure of your code especially in your style.css file
- good usage of flexbox's `order` property for your cards

**Comment by gak92** [comment]
Thanks

**Comment by elhamatokhi** [comment]
Great job!

-  Nice and neat code.
- Obvious presentation of your code.
- Considerable and organized code.
